
import "bootstrap/dist/css/bootstrap.rtl.min.css";
import "../globals.css";

export const metadata = {
  title: "Auth KFP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="">
        {children}
      </body>
    </html>
  );
}
