
import "bootstrap/dist/css/bootstrap.rtl.min.css";
import "./globals.css";
import Header from "./templates/Header";
import Footer from "./templates/Footer";
import SearchModalBtn from "./components/SearchModal/SearchModal";
import { UserProvider } from "@/context/UserContext";
export const metadata = {
  title: "KoushaFan Pars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="container-custom">
        <UserProvider>
          <Header />
          {children}
          <SearchModalBtn />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
